inherit_from: configs/ScanNet/scannet.yaml

mapping:
  bound: [ [-0.1, 8.6], [-0.1, 8.9], [-0.3, 3.3] ]
  marching_cubes_bound: [ [-0.1, 8.6], [-0.1, 8.9], [-0.3, 3.3] ]

data:
  datadir: D:\datasets\scannetv2\scans\scans_test\scene0000_00\frames
  trainskip: 1
  output: D:\datasets\scannetv2\scans\scans_test\scene0000_00\frames
  exp_name: "0"
  starting_frame: -1

tracking:
  iter_RO: 0
  iter: 10
  switch_interval: 90
  switch:
    align_threshold: 0.1

cam:
  near: 0
  far: 7

