inherit_from: configs/ScanNet/scannet.yaml

mapping:
  bound: [[-0.1, 8.6],[-0.1, 8.9],[-0.3, 3.3]]
  marching_cubes_bound: [[-0.1, 8.6],[-0.1, 8.9],[-0.3, 3.3]]
  iters: 10
  keyframe_every: 30  # insert keyframe at constant speed, default: 15
  min_cr_localMLP_len: [ 5., 5., 3. ]
  localMLP_max_len: [ 7., 7., 4. ]
  localMLP_max_len_back: [ 7., 7., 4. ]
  map_every: 3

grid:
  hash_size: 16
  use_bound_normalize: True

data:
  datadir: /media/javens/TYJ_lab1T/Dataset/ScanNet/all_sens/scans/scene0000_00/output
  trainskip: 1
  output: output/scannet/scene0000_00
  exp_name: "0"
  starting_frame: -1

tracking:
  iter_RO: 0  # iter num for RO
  iter: 10  # iter num for GO
  switch_interval: 90
  switch:
    align_threshold: 0.1

