inherit_from: configs/ScanNet/scannet.yaml

mapping:
  bound: [[-0.3, 7.4],[-0.3, 9.],[-0.3, 3.]]
  marching_cubes_bound: [[-0.3, 7.4],[-0.3, 9.],[-0.3, 3.]]

tracking:
  iter_RO: 0
  iter: 10

cam:
  near: 0
  far: 7

data:
  datadir: /media/javens/TYJ_lab1T/Dataset/ScanNet/all_sens/scans/scene0059_00/output
  trainskip: 1
  output: output/scannet/scene0059_00
  exp_name: "0"
  starting_frame: -1
