inherit_from: configs/ScanNet/scannet.yaml

mapping:
  bound: [[-0.3, 7.4],[-0.3, 9.],[-0.3, 3.]]
  marching_cubes_bound: [[-0.3, 7.4],[-0.3, 9.],[-0.3, 3.]]
  iters: 10
  keyframe_every: 30  # insert keyframe at constant speed
  min_cr_localMLP_len: [ 5., 5., 3. ]
  localMLP_max_len: [ 7., 7., 4. ]
  localMLP_max_len_back: [ 7., 7., 4. ]
  map_every: 2

tracking:
  iter_RO: 0
  iter: 10

grid:
  hash_size: 16

cam:
  near: 0
  far: 7

data:
  datadir: /media/javens/TYJ_lab1T/Dataset/ScanNet/all_sens/scans/scene0059_00/output
  trainskip: 1
  output: output/scannet/scene0059_00
  exp_name: "0"
  starting_frame: -1

training:
  rgb_weight: 1.
  depth_weight: 0.
  sdf_weight: 1000
  fs_weight: 10
