inherit_from: configs/TUM_RGBD/tum_rgbd.yaml

mapping:
  bound: [[-6.0, 6.0],[-5.0, 6.0],[-1.0, 3.0]]
  marching_cubes_bound: [[-6.0, 6.0],[-5.0, 6.0],[-1.0, 3.0]]

grid:
  hash_size: 16

data:
  datadir: /media/javens/rainbow7/Dataset/TUM_RGBD/fr3_office
  trainskip: 1
  output: output/TUM_RGBD/fr3_office
  exp_name: "0"
  starting_frame: -1

tracking:
  iter_RO: 5  # iter num for RO
  iter: 10  # iter num for GO

cam:  #intrinsic is different per scene in TUM
  H: 480
  W: 640
  fx: 535.4
  fy: 539.2
  cx: 320.1
  cy: 247.6
  crop_edge: 8
  crop_size: [ 384, 512 ]
  near: 0
  far: 5

