#dataset: 'fastcamo_synth'
dataset: 'tum_rgbd'

data:
  downsample: 1
  sc_factor: 1
  translation: 0
  num_workers: 4

sampling:
  n_rays_h: 16
  n_rays_w: 24
  kf_n_rays_h: 150  # default: 114
  kf_n_rays_w: 200  # default: 154

mapping:
  sample: 2000
  pixels_cur: 500  # default: 800
  first_mesh: True
  iters: 15
  lr_embed: 0.001
  lr_decoder: 0.001
  lr_rot: 0.001  # default: 0.001
  lr_trans: 0.001  # default: 0.001
  keyframe_every: 15  # insert keyframe at constant speed, default: 15
  min_containing_ratio: 0.75
  min_containing_ratio_mo: 0.9
  min_containing_ratio_back: 0.8
  min_cr_localMLP_len: [5., 5., 3.]
  localMLP_max_len: [6., 6., 4.]
  localMLP_max_len_back: [7., 7., 4.]
  map_every: 5
  localMLP_num: 10
  first_iters: 500
  optim_cur: False
  min_pixels_cur: 20
  map_accum_step: 1
  pose_accum_step: 5
  map_wait_step: 0
  filter_depth: False
  overlapping:
    n_rays_h: 24
    n_rays_w: 32
    min_pts: 200
  inactive:
    lr_rot: 0.001  # default: 0.001
    lr_trans: 0.001  # default: 0.001
    sleep_time: 1.
  global_BA:
    n_iter: 10
    interval: 10
    key_edge_weight: 0.1

tracking:
  iter_RO: 5  # iter num for RO
  iter: 10  # iter num for GO
  sample: 1000
  pc_samples: 40960
  lr_rot: 0.001  # default: 0.001
  lr_trans: 0.001  # default: 0.001
  ignore_edge_W: 20
  ignore_edge_H: 20
  iter_point: 0
  wait_iters: 100
  const_speed: True
  best: True
  switch_interval: 60
  RO:
    particle_size: 2000
    initial_scaling_factor: 0.02
    rescaling_factor: 0.5
    pixel_num: 400  # number of pixels sampled for each particle
    n_rows: 16
    n_cols: 24
    beta: 0.9
  switch:
    RO:
      particle_size: 2000
      initial_scaling_factor: 0.02
      rescaling_factor: 0.5
      pixel_num: 400  # number of pixels sampled for each particle
      beta: 0.9
    lr_rot: 0.001
    lr_trans: 0.001
    align_threshold: 0.05

grid:
  enc: 'HashGrid'
  tcnn_encoding: True
  hash_size: 19
  voxel_color: 0.08
  voxel_sdf: 0.04
  oneGrid: True
  use_bound_normalize: True

pos:
  enc: 'Frequency'
  n_bins: 8

decoder:
  geo_feat_dim: 15
  hidden_dim: 32
  num_layers: 2
  num_layers_color: 2
  hidden_dim_color: 32
  tcnn_network: False

cam:
  H: 480
  W: 640
  fx: 517.3
  fy: 516.5
  cx: 318.6
  cy: 255.3
  png_depth_scale: 5000.
  crop_edge: 0
  near: 0
  far: 5
  depth_trunc: 5.

training:
  rgb_weight: 1.
  depth_weight: 0.
  sdf_weight: 1000
  fs_weight: 10
  eikonal_weight: 0
  smooth_weight: 0.001  #0.001
  smooth_pts: 64
  smooth_vox: 0.1
  smooth_margin: 0.05
  n_samples_d: 50  # number of depth value sampled uniformly along a ray
  range_d: 0.2
  n_range_d: 25  # number of depth value sampled around surface along a ray
  n_importance: 0
  perturb: 1
  white_bkgd: False
  norm_factor: 1.
  trunc: 0.1
  rot_rep: 'quat'
  rgb_missing: 0.0
  classification: True

mesh:
  resolution: 512
  vis: 100
  ckpt_freq: 500
  voxel_eval: 0.05
  voxel_final: 0.05
  visualisation: False
  