inherit_from: configs/FastCaMo-synth/FastCaMo-synth.yaml

mapping:
  bound: [[-2.7, 7.8], [-1.3, 6.2], [-4.4, 2.45]]
  marching_cubes_bound: [[-2.7, 7.8], [-1.3, 6.2], [-4.4, 2.45]]

data:
  datadir: /media/javens/TYJ_lab1T/Dataset/FastCaMo-Synth/raw/frl_apartment_2
  trainskip: 1
  output: output/FastCaMo-synth/frl_apartment_2
  exp_name: "0"
  starting_frame: -1