dataset: "kinect"

data:
  downsample: 1
  sc_factor: 1
  translation: 0
  # num_workers: 1
  num_workers: 4


sampling:
  n_rays_h: 16
  n_rays_w: 24
  kf_n_rays_h: 150
  kf_n_rays_w: 200

mapping:
  sample: 1800
  pixels_cur: 800
  first_mesh: True
  iters: 15
  lr_embed: 0.01
  lr_decoder: 0.01
  lr_rot: 0.001  # default: 0.001
  lr_trans: 0.001  # default: 0.001
  keyframe_every: 15  # insert keyframe at constant speed
  min_containing_ratio: 0.75
  min_containing_ratio_mo: 0.8
  min_containing_ratio_back: 0.7
  min_cr_localMLP_len: [5., 5., 5.]
  localMLP_max_len: [7., 7., 7.]
  localMLP_max_len_back: [7., 7., 7.]
  map_every: 3
  localMLP_num: 10
  first_iters: 500
  optim_cur: False
  min_pixels_cur: 20
  map_accum_step: 1
  pose_accum_step: 5
  map_wait_step: 0
  overlapping:
    n_rays_h: 24
    n_rays_w: 32
    min_pts: 200
  inactive:
    lr_rot: 0.001  # default: 0.001
    lr_trans: 0.001  # default: 0.001
    sleep_time: 1.
  global_BA:
    n_iter: 10
    interval: 10
    key_edge_weight: 0.1

tracking:
  iter_RO: 5  # iter num for RO
  iter: 10  # iter num for GO
  sample: 1000
  pc_samples: 40960
  lr_rot: 0.001  # default: 0.001
  lr_trans: 0.001  # default: 0.001
  ignore_edge_W: 20
  ignore_edge_H: 20
  iter_point: 0
  wait_iters: 100
  const_speed: True
  best: True
  switch_interval: 30
  RO:
    particle_size: 2000
    initial_scaling_factor: 0.02
    rescaling_factor: 0.5
    n_rows: 16
    n_cols: 24
    beta: 0.9
  switch:
    lr_rot: 0.001
    lr_trans: 0.001
    align_threshold: 0.05
    including_last: 0
    min_correspondence: 2000
    min_trans_dist: 0.5
    map_num: 15

grid:
  enc: "HashGrid"
  tcnn_encoding: True
  hash_size: 19
  voxel_sdf: 0.04
  use_bound_normalize: True

pos:
  enc: "Frequency"
  n_bins: 8

cam:
  H: 3072
  W: 4096
  fx: 2044.0
  fy: 2042.8
  cx: 2048.8
  cy: 1560.4
  png_depth_scale: 1000. 
  crop_edge: 10
  near: 0
  far: 5
  depth_trunc: 100.

training:
  rgb_weight: 1.
  depth_weight: 0.
  sdf_weight: 1000
  fs_weight: 10
  n_samples_d: 50  # number of depth value sampled uniformly along a ray
  range_d: 0.2
  n_range_d: 25  # number of depth value sampled around surface along a ray
  perturb: 1
  norm_factor: 1.
  trunc: 0.1
  rgb_missing: 0.0
  classification: True

mesh:
  resolution: 512
  vis: 25
  ckpt_freq: 100
  voxel_final: 0.03
  simply_joint: False

  