inherit_from: configs/FastCaMo-synth/FastCaMo-synth.yaml

mapping:
  bound: [[-1.85, 1.8], [-6.95, 1.05], [-3.65, 1.35]]
  marching_cubes_bound: [[-1.85, 1.8], [-6.95, 1.05], [-3.65, 1.35]]

data:
  datadir: /media/javens/TYJ_lab1T/Dataset/FastCaMo-Synth/raw/room_0
  trainskip: 1
  output: output/FastCaMo-synth/room_0
  exp_name: "0"
  starting_frame: -1