inherit_from: configs/FastCaMo-large/FastCaMo-large.yaml

mapping:
  bound: [[-9.0, 2.5], [-1.2, 14.8], [-1.8, 11.4]]
  marching_cubes_bound: [[-9.0, 2.5], [-1.2, 14.8], [-1.8, 11.4]]
  localMLP_num: 20
  min_containing_ratio: 0.75
  min_containing_ratio_mo: 0.8
  min_containing_ratio_back: 0.9

grid:
  hash_size: 16

data:
  datadir: /media/javens/extra_space/Dataset/IndoorLarge_VF_NS/building2_f
  trainskip: 1
  output: output/FastCaMo-large/floor2
  exp_name: "0"
  starting_frame: -1