inherit_from: configs/FastCaMo-large/FastCaMo-large.yaml

mapping:
  bound: [[-9.0, 2.5], [-1.2, 14.8], [-1.8, 11.4]]
  marching_cubes_bound: [[-40., 100.], [-40., 100.], [-5., 20.]]
  localMLP_num: 50
  iters: 15
  keyframe_every: 15  # insert keyframe at constant speed
  min_cr_localMLP_len: [ 7., 7., 5. ]
  localMLP_max_len: [ 9., 9., 5. ]
  localMLP_max_len_back: [ 9., 9., 5. ]

grid:
  hash_size: 16

data:
  datadir: /media/javens/rainbow7/Dataset/floor1-3-try2
  trainskip: 1
  output: output/FastCaMo-large/floor1-3-try2
  exp_name: "0"
  starting_frame: -1