inherit_from: configs/FastCaMo-large/FastCaMo-large.yaml

mapping:
  bound: [[-3.1, 1.7], [-4.2, 8.0], [-1.2, 12.0]]
  marching_cubes_bound: [[-3.1, 1.7], [-4.2, 8.0], [-1.2, 12.0]]
  min_containing_ratio: 0.75
  min_containing_ratio_mo: 0.8
  min_containing_ratio_back: 0.75
  min_cr_localMLP_len: [ 5., 5., 5. ]
  localMLP_max_len: [ 7., 7., 5. ]
  localMLP_max_len_back: [ 7., 7., 5. ]

grid:
  hash_size: 16

data:
  datadir: /media/javens/TYJ_lab1T/Dataset/NS_VF/IndoorLarge/stairs2
  trainskip: 1
  output: output/FastCaMo-large/stairs2
  exp_name: "0"
  starting_frame: -1